sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12306LSr

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tHPkpvBZJrtsPeqoo4f
    access-key-secret: MSI5u3IYwuSGyHJ3lsD60QbJxrVVaw
    bucket-name: odentist-image-restore
